### ISSUE TITLE
请问作者大大能否提供使用data-value得到的内容加以渲染的小demo供以参考

### ISSUE THREAD

**Issue by J-StrawHat** [wangeditor-team/wangEditor-plugin-formula#1]
作者大大，在使用vue2.0中，通过formula插件获得HTML后，

由于得到的 LateX 格式的值在 `data-value` 中。我翻阅并尝试了非常多有关Katex的插件。

没有找到比较好的方案，既能够渲染普通的HTML标签，同时还能够渲染数学公式的需求。

+ 第一步 创建编辑器，并安装formula插件（封装成一个组件）

+ 第二步 将编辑器输入好的数学公式及文字，保存下来，传给父组件

+ 第三步 在父组件中，得到如下生成的HTML字符串 `str`

```javascript
str = '<h1>这个就是数学公式<span data-w-e-type="formula" data-w-e-is-void data-w-e-is-inline data-value="c = \\pm\\sqrt{a^2 + b^2}"></span></h1>'
var app = new Vue({
  el: '#app',
  data: {
    message: str
  }
})
```
现在想用v-html渲染成DOM元素，并且也想用katex渲染出数学公式，但无法兼得。

```html
<div id="app" 
  v-html="message"
  v-katex="{expression: message,
            options: { strict:false,throwOnError: false ,errorColor:'#666',colorIsTextColor:false}}">
</div>
```

**Comment by wangfupeng1988** [comment]
你可以像我一样，提前注册一个自定义 element `<w-e-formula-card>` 
https://github.com/wangeditor-team/wangEditor-plugin-formula/tree/main/src/register-custom-elem
 
然后把 `span[data-w-e-type="formula"]` 标签，转换为 `<w-e-formula-card>` ，再用 v-html 输出

**Comment by wangfupeng1988** [comment]
第一，先定义 custom element
第二，直接在页面中输出 HTML `<w-e-formula-card ...></<w-e-formula-card>` 即可

vue2 等框架，也都是 html 组成的。我能给提示的就这些了，如果还是不清楚的话，那可能真的是你前端并不熟练。

**Comment by wangfupeng1988** [comment]
想到一点。我打算等 V5 发布之后，自己利用业余时间做付费咨询。
看到你现在有问题，我也可以提前做一次付费咨询，或者付费开发 demo 。

价格上，大概符合一线城市高级研发工程师的工资，如果你有兴趣可以回复我。

**Comment by J-StrawHat** [comment]
感谢作者大大，换了mathjax后成功渲染了，我们还是在校学生，万分感激作者的解答。

**Comment by doYbest** [comment]
> 感谢作者大大，换了mathjax后成功渲染了，我们还是在校学生，万分感激作者的解答。
请问你的实现是在div中回显编辑器中输入的内容吗？是如何实现回显公式的同时保证markdown格式的渲染？
