### ISSUE TITLE
请问如果要定制弹出的公式输入对话框需要如何做

### ISSUE THREAD

**Issue by WangYingling** [wangeditor-team/wangEditor-plugin-formula#5]
![image](https://user-images.githubusercontent.com/23132769/184539713-2fcc225b-0883-409d-ad37-a17e422e9c57.png)

老师请问如果要把咱们这个插件的弹出框修改成如图说是的知乎的文章里的公式效果，能给提示下思路吗

**Comment by wangfupeng1988** [comment]
我也不知道思路。但我知道两点

1. 肯定能能实现
2. 需要你去详细看看扩展插件和模块的文档，详细看
